version: '3.8'

# Standalone Docker Compose
services:
  database:
    container_name: 'postgres-aiogram'
    image: 'postgres:14'
    restart: always
    networks:
      - tg-default
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_MAX_CONNECTIONS: 200
    volumes:
      - telegram-data:/var/lib/postgresql/data
      - ./deploy/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  telegram-bot:
    container_name: 'aiogram'
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=database
    command: [ "sh", "-c", "poetry run alembic upgrade head && poetry run python -m app " ]
    networks:
      - tg-default


networks:
  tg-default:
volumes:
  telegram-data: